/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        'base-100': 'var(--color-base-100)',
        'base-200': 'var(--color-base-200)',
        'base-300': 'var(--color-base-300)',
        'base-content': 'var(--color-base-content)',
        primary: 'var(--color-primary)',
        'primary-content': 'var(--color-primary-content)',
        secondary: 'var(--color-secondary)',
        'secondary-content': 'var(--color-secondary-content)',
        accent: 'var(--color-accent)',
        'accent-content': 'var(--color-accent-content)',
        neutral: 'var(--color-neutral)',
        'neutral-content': 'var(--color-neutral-content)',
        info: 'var(--color-info)',
        'info-content': 'var(--color-info-content)',
        success: 'var(--color-success)',
        'success-content': 'var(--color-success-content)',
        warning: 'var(--color-warning)',
        'warning-content': 'var(--color-warning-content)',
        error: 'var(--color-error)',
        danger: 'var(--color-error)',
        'error-content': 'var(--color-error-content)',
        'error-soft': 'var(--color-error-soft)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        muted: 'var(--color-muted)',
        border: 'var(--color-border)',
        text: 'var(--color-text)',
        overlay: 'var(--color-overlay)',
      },
    },
  },
  plugins: [],
}

